### ISSUE TITLE
Weekly REflection 13

### ISSUE THREAD

**Issue by HadesGeneral** [Berea-CS-Courses/capstone-project-HadesGeneral#20]
This is for Weekly Reflection 13.

I'd like suggestions on formating my document. Is all the information displayed in good ways, am I using markdown correctly, and am I using it all to the best that I can?

**Comment by belainehi** [comment]
HI Brian, I do not see a pull request for this reflection, which branch did you push it on?

**Comment by HadesGeneral** [comment]
It will be attached to the other one besides moan, weekly reflection 12 since I haven't had my previous issue looked at yet. I am currently in the process of making the goals for this week as well.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by belainehi** [comment]
Hi Brian, I forgot to approve your previous week 12  reflection after discussing it with you and the pod on Tuesday. But it's been approved now. Please post your reflection for week 13 as soon as you can as the deadline was on Friday.

**Comment by HadesGeneral** [comment]
I posted very soon after sending the previous email. Thank you.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by belainehi** [comment]
Hey Brian, your week 13's reflection was merged alongside your week 12's pull request, you can either reverse or delete it from the main branch as it's not been approved yet. Thanks.

**Comment by HadesGeneral** [comment]
I don't understand, I had to merge that one like you asked. And I had to create a file for 13 since with was due. So I merged 12, created changes on 13 to make a pull request. I'm not sure what the problem is.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HadesGeneral** [comment]
I did it.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by belainehi** [comment]
Week 13th reflection was merged to the main branch alongside the approved branch from week 12th. If you had left it and tried to merge it after approval it would have caused merge conflicts when you merge week 13th reflection. 

I see that you corrected it in this commit https://github.com/Berea-CS-Courses/capstone-project-HadesGeneral/commit/4c25864c8980c8edd6b5d4f480d76b64eacbbf4f . Thank you and keep up the great work!
