### ISSUE TITLE
[Deliverable 5]

### ISSUE THREAD

**Issue by HadesGeneral** [Berea-CS-Courses/capstone-project-HadesGeneral#22]
This document will be over Deliverable 5. This will have all the documentation and testing of my Robotic Skateboard.

I would like feedback on how I have formatted everything. The markdown formatting/ is there a better way to show all my data and documentation.

**Comment by belainehi** [comment]
https://github.com/Berea-CS-Courses/capstone-project-HadesGeneral/pull/21#issuecomment-834666449
