### ISSUE TITLE
[Deliverable # 1]

### ISSUE THREAD

**Issue by HadesGeneral** [Berea-CS-Courses/capstone-project-HadesGeneral#3]
This document outlines the specifications of my overall project and the scope of it all.

I would like feedback on how I have formatted the documents so far. I am fairly new to markdown.

**Comment by belainehi** [comment]
Good work setting the scope of what you think is achievable within this semester and projecting a possible next step of making it a self-driving skateboard that can support a skater. It's definitely clear that you have a clear goal of what you want your equipment to do, be able to support a lego's weight and be receptive to feedback from a remote control. A sketch or a simulation of how you want your equipment to move with the lego might be helpful as you work on building your project. It would also help to clarify the purpose of your project, remote control skateboards already exist and are already proven to work as toys.

**Comment by HadesGeneral** [comment]
Thank you, I'll keep all that in mind when going forward!
